framework:
    translator: { fallbacks: [ "fr" ] }
    secret: '%env(APP_SECRET)%'
    session:
        handler_id: ~

    php_errors:
        log: true

    cache:
    validation: { enable_annotations: true }


easy_admin:
    design:
        brand_color: '#424242'
    formats: 
        datetime: 'd/m/Y H:i:s'
    site_name: 'Danse Baby Danse !'
    entities:
        Contact:
            class: App\Entity\Contact
            list:
                title: "CONTACT : Messages reçus"
                actions: ['show', 'new', 'edit', 'search', 'delete']
                fields:
                    - { property: 'checked', type: 'toggle' }
                    - { property: 'id' }
                    - { property: 'firstName' }
                    - { property: 'lastName' }
                    - { property: 'email' }
                    - { property: 'phoneNumber' }
                    - { property: 'content' }
                    - { property: 'postedAt', type: 'datetime' }
            show:
                fields:
                    - { property: 'firstName' }
                    - { property: 'lastName' }
                    - { property: 'email' }
                    - { property: 'phoneNumber' }
                    - { property: 'content' }
                    - { property: 'postedAt', type: 'datetime' }
            edit:
                fields:
                    - { property: 'firstName' }
                    - { property: 'lastName' }
                    - { property: 'email' }
                    - { property: 'phoneNumber' }
                    - { property: 'content' }
                    - { property: 'postedAt', type: 'datetime' }                    
            new:
                fields:
                    - { property: 'id' }
                    - { property: 'firstName' }
                    - { property: 'lastName' }
                    - { property: 'email' }
                    - { property: 'phoneNumber' }
                    - { property: 'content' }
                    - { property: 'postedAt', type: 'datetime' }
        Actus:
            class: App\Entity\Actus
            list:
                title: "ACTUS : posts"
                actions: ['show', 'new', 'edit', 'search', 'delete']
                form:
                fields:
                    - { property: 'id'}
                    - { property: 'title'}
                    - { property: 'place'}
                    - { property: 'eventDate', type: 'datetime'}
                    - { property: 'content'}
                    - { property: 'price'}
                    - { property: 'urlImg', type: 'image', base_path: '%app.path.actus_images%'}
                    - { property: 'createdAt', type: 'datetime'}
            show:
                fields:
                    - { property: 'title'}
                    - { property: 'place'}
                    - { property: 'eventDate', type: 'datetime'}
                    - { property: 'content'}
                    - { property: 'price'}
                    - { property: 'urlImg', type: 'image', base_path: '%app.path.actus_images%'}
            edit:
                fields:
                    - { property: 'title'}
                    - { property: 'place'}
                    - { property: 'eventDate', type: 'datetime'}
                    - { property: 'content'}
                    - { property: 'price'}
                    #- { property: 'urlImg', type: 'image', base_path: '%app.path.actus_images%'}
                    - { property: 'imageFile', type: 'vich_image'}
            new:
                fields:
                    - { property: 'title'}
                    - { property: 'place'}
                    - { property: 'eventDate', type: 'datetime'}
                    - { property: 'content'}
                    - { property: 'price'}
                    #- { property: 'urlImg', type: 'image', base_path: '%app.path.actus_images%'}
                    - { property: 'imageFile', type: 'vich_image'}
                    - { property: 'createdAt', type: 'datetime'}
        Inscriptions:
            class: App\Entity\Inscriptions
            list:
                title: "Pré-inscriptions reçues"
                actions: ['show', 'new', 'edit', 'search', 'delete']
                fields:
                    - { property: 'checked', type: 'toggle' }
                    - { property: 'id' }
                    - { property: 'adult'}
                    - { property: 'firstName' }
                    - { property: 'lastName' }
                    - { property: 'phoneNumber' }
                    - { property: 'email' }
                    - { property: 'birthDate'}
                    - { property: 'grades' }
            show:
                fields:
                    - { property: 'adult'}
                    - { property: 'firstName' }
                    - { property: 'lastName' }
                    - { property: 'phoneNumber' }
                    - { property: 'email' }
                    - { property: 'birthDate'}
                    - { property: 'grades' }
            edit:
                fields:
                    - { property: 'adult'}
                    - { property: 'firstName' }
                    - { property: 'lastName' }
                    - { property: 'phoneNumber' }
                    - { property: 'email' }
                    - { property: 'birthDate'}
                    - { property: 'grades' }
            new:
                fields:
                    - { property: 'adult'}
                    - { property: 'firstName' }
                    - { property: 'lastName' }
                    - { property: 'phoneNumber' }
                    - { property: 'email' }
                    - { property: 'birthDate'}
                    - { property: 'grades' }




